#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

case "$1" in
  help | diun:help)
    help_content_func () {
      declare desc="return help_content string"
      cat<<help_content
    diun <app>, Says "diun <app>"
    diun:world, Says "diun world"
help_content
    }

    if [[ $1 = "diun:help" ]] ; then
        echo -e 'Usage: dokku diun[:world] [<app>]'
        echo ''
        echo 'Say diun World.'
        echo ''
        echo 'Example:'
        echo ''
        echo '$ dokku diun:world'
        echo 'diun world'
        echo ''
        echo 'Additional commands:'
        help_content_func | sort | column -c2 -t -s,
    else
        help_content_func
    fi
    ;;

  *)
    exit $DOKKU_NOT_IMPLEMENTED_EXIT
    ;;

esac
