#!/usr/bin/env bash

source "$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)")/config"
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x


update_dockerfiles() {
  declare APP="$1" DOCKER_IMAGE="$2"
  echo "- name: ${DOCKER_IMAGE}" > "${CONFIG_DIR}/${CONFIG_FILE}"
  echo "FROM ${DOCKER_IMAGE}" > "${CONFIG_DIR}/${APP}.dockerfile"
}


update_dockerfiles "$@"

