#!/usr/bin/env bash


$DOCKER_BIN stop dokku-diun && $DOCKER_BIN rm dokku-diun

CONFIG_DIR="/var/lib/dokku/data/diun"

DIUN_IMAGE="crazymax/diun:latest"
DIUN_COMMAND="serve"

mkdir $CONFIG_DIR
chown -R "${DOKKU_SYSTEM_USER}:${DOKKU_SYSTEM_GROUP}" $CONFIG_DIR

$DOCKER_BIN  run -d --name dokku-diun \
	-v ${CONFIG_DIR}:/dockerfiles \
	-v /var/run/docker.sock:/var/run/docker.sock \
	-e DIUN_PROVIDERS_DOCKERFILE_PATTERNS=/dockerfiles/*.dockerfile \
	-e TZ=Europe/Rome \
	-e LOG_LEVEL=info \
	-e LOG_JSON=false \
	-e DIUN_WATCH_WORKERS=20 \
	-e "DIUN_WATCH_SCHEDULE=*/1 * * * *" \
	-e DIUN_WATCH_JITTER=30s \
	--restart always \
	$DIUN_IMAGE $DIUN_COMMAND
