#!/usr/bin/env bash

source "$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)")/diun/configs"
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

remove_dockerfile() {
  declare APP="$1"
  rm -rf "${CONFIG_DIR}/${APP}.dockerfile"
}

remove_dockerfile "$@"
